### ISSUE TITLE
Nested labels don't work

### ISSUE THREAD

**Issue by LukeTowers** [shellscape/gmail-classic#4]
The current CSS completely removes the dropdown buttons for nested labels, this renders it impossible to access the sublabels through the UI.

**Comment by shellscape** [comment]
Bummer. Screenshot(s) would help folks diagnose and fix the issue you're experiencing.

**Comment by LukeTowers** [comment]
@shellscape awesome, thanks for the fix! Will it get populated in the chrome extension?

**Comment by shellscape** [comment]
yessir. when you see a `chore(release)` commit, that means that the extension was built and updated. the extension version will also match the release version here.

**Comment by LukeTowers** [comment]
Awesome, thanks for your work on this! As a side note, would you be willing to add support for the dark theme?

**Comment by shellscape** [comment]
That'll be tricky. I never used the dark theme, and I don't have access to the source css for that. If it was contributed to the project, I'd be open to it.

**Comment by LukeTowers** [comment]
WIP for dark theme:

```css
.gb_Ld.gb_je.gb_Td.gb_le {
    background: #000;
}

.nH.oy8Mbf.qp {
    background: #000;
}

header[role="banner"] {
    background: #000 !important;
    border-bottom: 1px solid rgba(255,255,255,0.25);
}

.gb_Dc.gb_2d.gb_ce.gb_9d {
    border-radius: 0 !important;
}

#aso_search_form_anchor {
    border-radius: 0 !important;
    background-color: rgba(255,255,255,0.25) !important;
}

#aso_search_form_anchor .gb_jf {
    color: #FFF !important;
}

body[jsaction] [data-collapsed-nav-tooltip][data-tooltip-suspended] div div.aio div:last-child {
    color: #FFF;
}

.nU {
    color: #FFF !important;
}

body[jsaction] [role="navigation"] a {
    color: #eee !important;
}

.TI .T-I-ax7, .z0 .T-I-ax7, .G-atb .T-I-ax7, .Bn {
    background-image: linear-gradient(to bottom, rgba(68,68,68,.75),  rgba(60,60,60,0.75)) !important;
}

body[jsaction] .ain [data-collapsed-nav-tooltip][data-tooltip] > div::before {
    border-color: #FFF !important;
}

.nZ.aiq {
    border-color: #FFF !important;
    background: #000 !important;
}

body[jsaction] .ain [data-collapsed-nav-tooltip][data-tooltip] > div a {
    color: inherit !important;
}

body[jsaction] .ain [data-collapsed-nav-tooltip][data-tooltip] > div > div:nth-child(3) div {
    color: inherit !important;
}

body[jsaction] .ain [data-collapsed-nav-tooltip][data-tooltip] > div {
    background: transparent;
}

body[jsaction] [gh="cm"] {
    background-color: #f5f5f5 !important;
    background-image: linear-gradient(to bottom, #f5f5f5, #f1f1f1) !important;
    border: 1px solid rgba(0,0,0,0.1) !important;
    color: #444 !important;
}

.gb_Ra {
    background: transparent !important;
}
```
